<a href="https://colab.research.google.com/github/divyalaldinani/Deep-Learning-in-TensorFlow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.17.1


## tf.constant

In [2]:
scalar = tf.constant(7) #to create a constant/immutable tensor
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [4]:
vector = tf.constant([10, 10], dtype = 'float32')
vector

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10., 10.], dtype=float32)>

In [5]:
vector.ndim

1

In [6]:
matrix =tf.constant([[10.0, 10.1],[10.98, 10.6]])

In [7]:
matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10.  , 10.1 ],
       [10.98, 10.6 ]], dtype=float32)>

In [8]:
print(matrix.ndim) #number of elements in shape
print(matrix.shape)
print(matrix.dtype)

2
(2, 2)
<dtype: 'float32'>


In [9]:
tensor = tf.constant([[[1,2,3], #dim = number of square brackets opening in the start
                       [4,5,6]],
                      [[7, 8, 9],
                       [10, 11, 12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

##tf.Variable()

In [10]:
variable_tensor = tf.Variable([10, 7])
constant_tensor = tf.constant([10, 9])

In [11]:
variable_tensor, constant_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  9], dtype=int32)>)

In [12]:
variable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [13]:
# variable_tensor[0] = 8 # ERROR
variable_tensor[0].assign(8)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([8, 7], dtype=int32)>

In [14]:
# constant_tensor[0].assign[12] #ERROR

## Creating random tensors (arbitrary size with random numbers)

In [15]:
#follows uniform distribution
tf.random.set_seed(42) #ensures that the same random numbers are generated every time the code is run
random_1 = tf.random.uniform(shape=(3, 2, 4))
random_3 = tf.random.uniform(shape=(3, 2, 4))


In [16]:
random_1, random_3

(<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
 array([[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255],
         [0.03366041, 0.68467236, 0.74011743, 0.8724445 ]],
 
        [[0.22632635, 0.22319686, 0.3103881 , 0.7223358 ],
         [0.13318717, 0.5480639 , 0.5746088 , 0.8996835 ]],
 
        [[0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ],
         [0.72942245, 0.54583454, 0.10756552, 0.6767061 ]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
 array([[[0.68789124, 0.48447883, 0.9309944 , 0.252187  ],
         [0.73115396, 0.89256823, 0.94674826, 0.7493341 ]],
 
        [[0.34925628, 0.54718256, 0.26160395, 0.69734323],
         [0.11962581, 0.53484344, 0.7148968 , 0.87501776]],
 
        [[0.33967495, 0.17377627, 0.4418521 , 0.9008261 ],
         [0.13803864, 0.12217975, 0.5754491 , 0.9417181 ]]], dtype=float32)>)

In [17]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2, 4))
random_2

<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ,  0.09988727, -0.50998646]],

       [[-0.7535806 , -0.5716629 ,  0.1480774 , -0.23362991],
        [-0.3522796 ,  0.40621266, -1.0523509 ,  1.2054597 ]],

       [[ 1.6874489 , -0.44629744, -2.3410842 ,  0.99009085],
        [-0.08763231, -0.635568  , -0.6161736 , -1.9441465 ]]],
      dtype=float32)>

In [18]:
random_1 == random_3

<tf.Tensor: shape=(3, 2, 4), dtype=bool, numpy=
array([[[False, False, False, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [False, False, False, False]]])>

##shuffle the tensor

In [19]:
tensor = tf.constant([[10, 8],[9,4],[6,5]])
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  8],
       [ 9,  4],
       [ 6,  5]], dtype=int32)>

In [20]:
tf.random.set_seed(42)
shuffled_tensor = tf.random.shuffle(tensor) #shuffles along 1st dim
#set both global and operational level seed to get 100% reproducibility
shuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 9,  4],
       [ 6,  5],
       [10,  8]], dtype=int32)>

## Other ways to make tensors

In [21]:
tf.ones((2,4,5))

<tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [22]:
tf.zeros((2, 3, 2))

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)>

## tensors attributes



In [23]:
tensor.shape

TensorShape([3, 2])

In [24]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [25]:
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  8],
       [ 9,  4],
       [ 6,  5]], dtype=int32)>

In [26]:
tensor.ndim #rank

2

In [27]:
print(tensor[0])

tf.Tensor([10  8], shape=(2,), dtype=int32)


In [28]:
tensor.dtype

tf.int32

## manipulating tensors(tensor operations)
**Basic Operations:** +, -, *, /

In [29]:
tensor  = tf.random.uniform(shape=(3,4,3), minval = 1, maxval = 17, dtype = 'int32')


In [30]:
tensor.dtype

tf.int32

In [31]:
tensor

<tf.Tensor: shape=(3, 4, 3), dtype=int32, numpy=
array([[[ 3,  8,  4],
        [11,  5, 14],
        [13, 15, 15],
        [ 5, 14, 12]],

       [[ 7,  1, 14],
        [ 6,  9, 14],
        [13,  6,  1],
        [ 7,  2,  9]],

       [[11,  7, 14],
        [ 8,  9,  5],
        [11, 10, 14],
        [ 2,  4,  8]]], dtype=int32)>

In [32]:
tensor + 10

<tf.Tensor: shape=(3, 4, 3), dtype=int32, numpy=
array([[[13, 18, 14],
        [21, 15, 24],
        [23, 25, 25],
        [15, 24, 22]],

       [[17, 11, 24],
        [16, 19, 24],
        [23, 16, 11],
        [17, 12, 19]],

       [[21, 17, 24],
        [18, 19, 15],
        [21, 20, 24],
        [12, 14, 18]]], dtype=int32)>

In [33]:
tensor * 2

<tf.Tensor: shape=(3, 4, 3), dtype=int32, numpy=
array([[[ 6, 16,  8],
        [22, 10, 28],
        [26, 30, 30],
        [10, 28, 24]],

       [[14,  2, 28],
        [12, 18, 28],
        [26, 12,  2],
        [14,  4, 18]],

       [[22, 14, 28],
        [16, 18, 10],
        [22, 20, 28],
        [ 4,  8, 16]]], dtype=int32)>

In [34]:
tensor #original tensor remains unchanged

<tf.Tensor: shape=(3, 4, 3), dtype=int32, numpy=
array([[[ 3,  8,  4],
        [11,  5, 14],
        [13, 15, 15],
        [ 5, 14, 12]],

       [[ 7,  1, 14],
        [ 6,  9, 14],
        [13,  6,  1],
        [ 7,  2,  9]],

       [[11,  7, 14],
        [ 8,  9,  5],
        [11, 10, 14],
        [ 2,  4,  8]]], dtype=int32)>

In [35]:
tensor/10

<tf.Tensor: shape=(3, 4, 3), dtype=float64, numpy=
array([[[0.3, 0.8, 0.4],
        [1.1, 0.5, 1.4],
        [1.3, 1.5, 1.5],
        [0.5, 1.4, 1.2]],

       [[0.7, 0.1, 1.4],
        [0.6, 0.9, 1.4],
        [1.3, 0.6, 0.1],
        [0.7, 0.2, 0.9]],

       [[1.1, 0.7, 1.4],
        [0.8, 0.9, 0.5],
        [1.1, 1. , 1.4],
        [0.2, 0.4, 0.8]]])>

###using inbuilt tf functions

In [36]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(3, 4, 3), dtype=int32, numpy=
array([[[ 30,  80,  40],
        [110,  50, 140],
        [130, 150, 150],
        [ 50, 140, 120]],

       [[ 70,  10, 140],
        [ 60,  90, 140],
        [130,  60,  10],
        [ 70,  20,  90]],

       [[110,  70, 140],
        [ 80,  90,  50],
        [110, 100, 140],
        [ 20,  40,  80]]], dtype=int32)>

In [37]:
tensor #org tensor -> unchanged

<tf.Tensor: shape=(3, 4, 3), dtype=int32, numpy=
array([[[ 3,  8,  4],
        [11,  5, 14],
        [13, 15, 15],
        [ 5, 14, 12]],

       [[ 7,  1, 14],
        [ 6,  9, 14],
        [13,  6,  1],
        [ 7,  2,  9]],

       [[11,  7, 14],
        [ 8,  9,  5],
        [11, 10, 14],
        [ 2,  4,  8]]], dtype=int32)>

In [38]:
tf.add(tensor, -9)

<tf.Tensor: shape=(3, 4, 3), dtype=int32, numpy=
array([[[-6, -1, -5],
        [ 2, -4,  5],
        [ 4,  6,  6],
        [-4,  5,  3]],

       [[-2, -8,  5],
        [-3,  0,  5],
        [ 4, -3, -8],
        [-2, -7,  0]],

       [[ 2, -2,  5],
        [-1,  0, -4],
        [ 2,  1,  5],
        [-7, -5, -1]]], dtype=int32)>

In [39]:
tf.divide(tensor, 5)

<tf.Tensor: shape=(3, 4, 3), dtype=float64, numpy=
array([[[0.6, 1.6, 0.8],
        [2.2, 1. , 2.8],
        [2.6, 3. , 3. ],
        [1. , 2.8, 2.4]],

       [[1.4, 0.2, 2.8],
        [1.2, 1.8, 2.8],
        [2.6, 1.2, 0.2],
        [1.4, 0.4, 1.8]],

       [[2.2, 1.4, 2.8],
        [1.6, 1.8, 1. ],
        [2.2, 2. , 2.8],
        [0.4, 0.8, 1.6]]])>

## Matrix Multiplication

In [40]:
a = tf.random.uniform(shape=(3,4), minval = 1, maxval = 20, dtype = 'int32')
b = tf.random.uniform(shape=(4,5), minval = 1, maxval = 20, dtype = 'int32')

In [41]:
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[16,  6, 11, 12],
       [18, 17, 12,  3],
       [ 1,  9,  7, 19]], dtype=int32)>

In [42]:
b

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[18,  6, 17, 19, 13],
       [ 2, 15,  5,  9,  9],
       [17,  1,  6, 12,  6],
       [14,  7, 13,  3,  6]], dtype=int32)>

In [43]:
# c = tf.matmul(a, b)
c = a @ b

In [44]:
c

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[655, 281, 524, 526, 400],
       [604, 396, 502, 648, 477],
       [421, 281, 351, 241, 250]], dtype=int32)>

In [45]:
c = tf.matmul(a, b) #must be compatible

In [46]:
c

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[655, 281, 524, 526, 400],
       [604, 396, 502, 648, 477],
       [421, 281, 351, 241, 250]], dtype=int32)>

In [47]:
X = tf.constant([[1,2,4],[2,5,6]])
X

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [2, 5, 6]], dtype=int32)>

In [48]:
a = tf.random.uniform(shape=(3,4,5), minval = 1, maxval = 20, dtype = 'int32')
b = tf.random.uniform(shape=(3,5,6), minval = 1, maxval = 20, dtype = 'int32')

In [49]:
c = a @ b

In [50]:
c

<tf.Tensor: shape=(3, 4, 6), dtype=int32, numpy=
array([[[406, 293, 499, 420, 394, 505],
        [249, 339, 453, 306, 377, 427],
        [197, 257, 475, 306, 321, 305],
        [517, 443, 677, 500, 500, 686]],

       [[487, 299, 342, 337, 417, 467],
        [684, 470, 534, 576, 700, 743],
        [733, 423, 533, 541, 672, 712],
        [581, 423, 453, 202, 305, 627]],

       [[520, 558, 162, 642, 523, 485],
        [396, 394, 120, 501, 378, 395],
        [621, 670, 372, 644, 530, 358],
        [618, 602, 288, 628, 569, 467]]], dtype=int32)>

In [51]:
c.shape

TensorShape([3, 4, 6])

**Tensor with ndim = 3
Dim of A = (d1, d2, d3)
Dim of B = (d1, d3, d4), Resulting shape = (d1, d2, d4)**


**Tensor with ndim = 4
Dim of A = (d1, d2, d3, d4)
Dim of B = (d1, d2, d4, d5), Resulting shape = (d1, d2, d3, d5)**

##Changing shape of tensors after creation

In [52]:
tf.reshape(c, shape = (6,6,2)) #no of elems iniotially = number of elems finally

<tf.Tensor: shape=(6, 6, 2), dtype=int32, numpy=
array([[[406, 293],
        [499, 420],
        [394, 505],
        [249, 339],
        [453, 306],
        [377, 427]],

       [[197, 257],
        [475, 306],
        [321, 305],
        [517, 443],
        [677, 500],
        [500, 686]],

       [[487, 299],
        [342, 337],
        [417, 467],
        [684, 470],
        [534, 576],
        [700, 743]],

       [[733, 423],
        [533, 541],
        [672, 712],
        [581, 423],
        [453, 202],
        [305, 627]],

       [[520, 558],
        [162, 642],
        [523, 485],
        [396, 394],
        [120, 501],
        [378, 395]],

       [[621, 670],
        [372, 644],
        [530, 358],
        [618, 602],
        [288, 628],
        [569, 467]]], dtype=int32)>

In [53]:
tensor = tf.constant([[ 3,  8,  4],
        [11,  5, 14],
        [13, 15, 15],
        [ 5, 14, 12]])

In [54]:
tf.transpose(tensor)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 3, 11, 13,  5],
       [ 8,  5, 15, 14],
       [ 4, 14, 15, 12]], dtype=int32)>

In [55]:
a, tf.transpose(a, perm=[2,0,1]) #reorder the axes -> initially it was 0,1,2

(<tf.Tensor: shape=(3, 4, 5), dtype=int32, numpy=
 array([[[11, 11,  7,  5, 14],
         [ 2, 14,  5, 12, 10],
         [ 3,  7,  3, 10, 17],
         [ 9, 16, 12, 14, 15]],
 
        [[ 7,  4, 10,  8,  9],
         [ 9,  1, 18, 12, 19],
         [15,  1, 19,  7, 17],
         [ 2, 15, 18,  1,  6]],
 
        [[15,  7,  3, 17,  4],
         [12,  1,  3, 15,  3],
         [ 1,  4, 13, 17, 13],
         [ 9,  3, 13, 15,  8]]], dtype=int32)>,
 <tf.Tensor: shape=(5, 3, 4), dtype=int32, numpy=
 array([[[11,  2,  3,  9],
         [ 7,  9, 15,  2],
         [15, 12,  1,  9]],
 
        [[11, 14,  7, 16],
         [ 4,  1,  1, 15],
         [ 7,  1,  4,  3]],
 
        [[ 7,  5,  3, 12],
         [10, 18, 19, 18],
         [ 3,  3, 13, 13]],
 
        [[ 5, 12, 10, 14],
         [ 8, 12,  7,  1],
         [17, 15, 17, 15]],
 
        [[14, 10, 17, 15],
         [ 9, 19, 17,  6],
         [ 4,  3, 13,  8]]], dtype=int32)>)

**Dot Product**

In [56]:
a = tf.random.uniform(shape=(3,4), minval = 1, maxval = 20, dtype = 'int32')
b = tf.random.uniform(shape=(3,4), minval = 1, maxval = 20, dtype = 'int32')

In [57]:
c = tf.matmul(a, tf.transpose(b))

In [58]:
c

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[570, 510, 584],
       [516, 368, 395],
       [694, 741, 762]], dtype=int32)>

In [59]:
c = tf.tensordot(a, tf.transpose(b), axes = 1)

In [60]:
c

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[570, 510, 584],
       [516, 368, 395],
       [694, 741, 762]], dtype=int32)>

In [61]:
c = tf.matmul(a, tf.reshape(b, shape = (4,3)))

In [62]:
c

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[408, 728, 474],
       [334, 606, 348],
       [533, 958, 661]], dtype=int32)>

**Note**: **Matrix mult and dot product gives different ans**


**reshape and transpose are diff**


In [63]:
A = tf.constant([1.9, 7.4])
A

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.9, 7.4], dtype=float32)>

In [64]:
A = tf.cast(A, dtype = tf.float16)

In [65]:
A

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.9, 7.4], dtype=float16)>

In [66]:
A = tf.constant([1, 8, 5])
A = tf.cast(A, dtype = 'float16')

In [67]:
A

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1., 8., 5.], dtype=float16)>

##tensor aggregation
####Aggregating tensors means combining multiple tensors into a single tensor or performing an operation that summarizes their information. This can be achieved using operations like concatenation, stacking, summing, averaging, or reducing along specific dimensions.

In [68]:
D = tf.constant([-7, -9, -5])
D

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-7, -9, -5], dtype=int32)>

In [69]:
tf.abs(D)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 9, 5], dtype=int32)>

In [70]:
D = tf.cast(D, dtype = 'float32')

In [71]:
D = tf.random.uniform(shape = (4, 8,4), minval = 0, maxval = 100)

min = tf.reduce_min(D)
max = tf.reduce_max(D)
mean = tf.reduce_mean(D)
avg = tf.reduce_sum(D)
min, max, mean, avg

(<tf.Tensor: shape=(), dtype=float32, numpy=0.8735776>,
 <tf.Tensor: shape=(), dtype=float32, numpy=99.51719>,
 <tf.Tensor: shape=(), dtype=float32, numpy=51.689484>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6616.254>)

In [72]:
import numpy as np

E = tf.constant(np.random.randint(0, 100, size = 45))


In [73]:

min = tf.reduce_min(E)
max = tf.reduce_max(E)
mean = tf.reduce_mean(E)
avg = tf.reduce_sum(E)
min, max, mean, avg

(<tf.Tensor: shape=(), dtype=int64, numpy=2>,
 <tf.Tensor: shape=(), dtype=int64, numpy=97>,
 <tf.Tensor: shape=(), dtype=int64, numpy=41>,
 <tf.Tensor: shape=(), dtype=int64, numpy=1876>)

In [74]:
var = tf.math.reduce_variance(D)
std_dev = tf.math.reduce_std(D)
var, std_dev

(<tf.Tensor: shape=(), dtype=float32, numpy=884.36>,
 <tf.Tensor: shape=(), dtype=float32, numpy=29.73819>)

###Importing tfp(tf prob.)

In [75]:
import tensorflow_probability as tfp

tfp.stats.variance(D), tfp.stats.stddev(D)

(<tf.Tensor: shape=(8, 4), dtype=float32, numpy=
 array([[ 766.9315  ,  101.1458  ,  409.2265  ,  291.912   ],
        [ 428.6458  , 1538.2792  ,  780.9971  ,   48.345398],
        [ 737.2733  ,  994.10626 ,  346.36884 ,  708.4374  ],
        [ 773.3486  , 1197.5247  ,  364.05737 ,  866.9276  ],
        [ 474.99173 ,  619.7938  ,  352.97144 ,  504.25897 ],
        [ 209.40121 ,  637.6605  ,  923.5344  , 1339.3877  ],
        [ 302.76498 ,  831.16113 , 1119.1671  ,  285.5303  ],
        [1088.4104  , 1012.91003 , 1153.9266  , 1414.6255  ]],
       dtype=float32)>,
 <tf.Tensor: shape=(8, 4), dtype=float32, numpy=
 array([[27.69353  , 10.057127 , 20.229347 , 17.085432 ],
        [20.703762 , 39.2209   , 27.946323 ,  6.9530854],
        [27.152777 , 31.52945  , 18.610987 , 26.616488 ],
        [27.809145 , 34.60527  , 19.080288 , 29.443634 ],
        [21.794304 , 24.895658 , 18.787533 , 22.455711 ],
        [14.470702 , 25.251942 , 30.38971  , 36.597645 ],
        [17.400143 , 28.829865 , 

In [76]:
tf.math.reduce_variance(tf.cast(E, dtype='float32'))

<tf.Tensor: shape=(), dtype=float32, numpy=700.2143>

In [77]:
tf.math.reduce_std(tf.cast(E, dtype='float32'))

<tf.Tensor: shape=(), dtype=float32, numpy=26.461563>

In [78]:
tfp.stats.variance(tf.cast(E, dtype='float32'))

<tf.Tensor: shape=(), dtype=float32, numpy=700.2143>

In [79]:
tfp.stats.stddev(tf.cast(E, dtype='float32'))

<tf.Tensor: shape=(), dtype=float32, numpy=26.461563>

###Positional min and max of a tensor:
####at which index does the max value occur

---



In [80]:
# to get max/min value in a tensor along an axes
F = tf.random.uniform(shape = (50,))
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([1.27802730e-01, 8.62301230e-01, 4.15632963e-01, 1.00286722e-01,
       6.07836485e-01, 7.90521741e-01, 6.06833696e-02, 8.56746435e-01,
       7.20012665e-01, 6.80043340e-01, 3.18007350e-01, 9.15518522e-01,
       9.83233213e-01, 9.49099660e-01, 9.27690983e-01, 4.26432252e-01,
       1.65649414e-01, 5.96877337e-02, 1.01531982e-01, 3.48368764e-01,
       1.06096268e-05, 5.53984642e-01, 1.04559660e-02, 1.70157075e-01,
       5.35020947e-01, 3.53641510e-02, 5.11248112e-02, 3.47512603e-01,
       4.17755604e-01, 4.66669559e-01, 9.22843099e-01, 6.48598909e-01,
       3.84631276e-01, 7.53028631e-01, 9.17651892e-01, 5.70779085e-01,
       9.69477892e-02, 4.58525062e-01, 2.72809863e-01, 7.18811393e-01,
       6.84959650e-01, 9.46360826e-01, 6.96492195e-02, 1.22516274e-01,
       5.67929626e-01, 6.14467025e-01, 2.55180240e-01, 7.69669652e-01,
       3.94763947e-01, 6.69542074e-01], dtype=float32)>

In [81]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=12>

In [82]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9832332>

In [83]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9832332>

In [84]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=20>

In [85]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0609627e-05>

In [86]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0609627e-05>

### removing all single dims

In [87]:
G = tf.constant(tf.random.uniform(shape=(50,)), shape = (2, 1, 25))

In [88]:
G

<tf.Tensor: shape=(2, 1, 25), dtype=float32, numpy=
array([[[0.5749372 , 0.19900596, 0.7038239 , 0.05541027, 0.5884645 ,
         0.5430788 , 0.9185413 , 0.37144518, 0.84554374, 0.9902985 ,
         0.27800095, 0.5500362 , 0.43682623, 0.68426645, 0.22095895,
         0.46595943, 0.2495377 , 0.36201143, 0.64489734, 0.02396476,
         0.6864866 , 0.11819983, 0.9782574 , 0.5938797 , 0.09975135]],

       [[0.8805319 , 0.5449954 , 0.4293872 , 0.3130728 , 0.3187188 ,
         0.81566787, 0.41933835, 0.23228383, 0.6060114 , 0.821591  ,
         0.8203496 , 0.7298629 , 0.10527313, 0.43954647, 0.33358395,
         0.14798844, 0.2402767 , 0.23390472, 0.89162004, 0.31298292,
         0.23591721, 0.05167186, 0.2891872 , 0.7042843 , 0.3477949 ]]],
      dtype=float32)>

In [89]:
G = tf.squeeze(G)
G
#removing dim of size 1 from tensor

<tf.Tensor: shape=(2, 25), dtype=float32, numpy=
array([[0.5749372 , 0.19900596, 0.7038239 , 0.05541027, 0.5884645 ,
        0.5430788 , 0.9185413 , 0.37144518, 0.84554374, 0.9902985 ,
        0.27800095, 0.5500362 , 0.43682623, 0.68426645, 0.22095895,
        0.46595943, 0.2495377 , 0.36201143, 0.64489734, 0.02396476,
        0.6864866 , 0.11819983, 0.9782574 , 0.5938797 , 0.09975135],
       [0.8805319 , 0.5449954 , 0.4293872 , 0.3130728 , 0.3187188 ,
        0.81566787, 0.41933835, 0.23228383, 0.6060114 , 0.821591  ,
        0.8203496 , 0.7298629 , 0.10527313, 0.43954647, 0.33358395,
        0.14798844, 0.2402767 , 0.23390472, 0.89162004, 0.31298292,
        0.23591721, 0.05167186, 0.2891872 , 0.7042843 , 0.3477949 ]],
      dtype=float32)>

### one hot encoding: form of numerical encoding

In [90]:
list = [0,1,3,2]
tf.one_hot(list, depth=4)  #produces 4*4 matrix

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]], dtype=float32)>

In [91]:
tf.one_hot(list, depth=3)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]], dtype=float32)>

In [92]:
tf.one_hot(list, depth = 4, on_value = 'green', off_value='red') #   1 -> green, 0 -> red, notice the dtype

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'green', b'red', b'red', b'red'],
       [b'red', b'green', b'red', b'red'],
       [b'red', b'red', b'red', b'green'],
       [b'red', b'red', b'green', b'red']], dtype=object)>

### few mathematical ops

In [93]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [94]:
I = tf.tensordot( H , H, axes = 0 )
I

<tf.Tensor: shape=(9, 9), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]], dtype=int32)>

In [95]:
I = tf.square(H)
I

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [96]:
tf.sqrt(tf.cast(H, dtype = 'float32'))  # matrix with data type : float, double

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [97]:
tf.math.log(tf.cast(H, dtype = 'float32')) # float/doubel type matrix passed as arg

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

In [98]:
# numpy array to tensor
J = tf.constant(np.array([3,9,13]))
J

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 3,  9, 13])>

In [99]:
np.array(J), type(np.array(J))

(array([ 3,  9, 13]), numpy.ndarray)

In [100]:
# tensor to numpy array
J.numpy(), type(J.numpy())

(array([ 3,  9, 13]), numpy.ndarray)

In [101]:
# data type diff bw numpy tensor and tf tensor
numpy_arr = tf.constant(np.array([3., 8., 2.]))
tensor_arr = tf.constant([3., 8., 2.])
numpy_arr.dtype, tensor_arr.dtype

(tf.float64, tf.float32)

## finding access to GPUs

In [102]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [103]:
!nvidia-smi

Sun Dec 15 06:39:06 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P0              28W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--